algoritmo "Nome do Programa"
//Faça um programa que leia um número inteiro e determine se ele é divisível por 5 utilizando o operador de resto. Mostre "Divisível por 5" ou "Não divisível por 5"
var

numero,numero_divisivel5:inteiro

inicio
escreva("digite um número: ")
leia(numero)

numero_divisivel5 <- numero % 5
    se numero_divisivel5=0 entao
       escreva("o número é divísível por 5")
    senao
       escreva("o número não é divisivel por 5")
    fimSe
fimalgoritmo