algoritmo "Nome do Programa"
//Crie um programa que verifique se uma pessoa é maior de idade e está empregada.
var
idade:inteiro


inicio
escreva("digite a sua idade: ")
leia(idade)

se (idade <= 0 ou idade>=65) entao
   escreva("idade inválida (não nasceu,aposentado ou morto.) Tente novamente")
senao se (idade>=18) entao
   escreva("está empregada")
senao
   escreva("não está empregada")
fimSe
fimSe


fimalgoritmo