Algoritmo "algoritmo20"

Var
diasmensal: real
salario:real
diadetrabalho:real
horapordia: real
valorhoratrabalhada:real

Inicio
horapordia<-8
valorhoratrabalhada<-25.00
diadetrabalho<-horapordia*valorhoratrabalhada

escreva("Digite o numero de dias que voce trabalha em um mes: ")
leia(diasmensal)
salario<-diasmensal*diadetrabalho
escreva("O salário do funcionario é: R$ ",salario)
Fimalgoritmo