algoritmo "Nome do Programa"
// 
var
numero,contador,subtracao,subtracao:real


inicio
contador<-1


enquanto (contador<=2) faca
    escreval ("Digite o numero: ")
    leia(numero)
    se (numero<subtracao) entao
        subtracao<-(numero-subtracao)*(-1)
    senao
         subtracao<-(numero+subtracao)*(-1)
    fimse
    contador<-contador+1
fimenquanto
escreva(subtracao)

fimalgoritmo