Algoritmo "algoritmo29"

// Disciplina   : [Linguagem e Logica de Programacoo] 
// Professor   : Antonio Carlos Nicolodi 
//Escreva um algoritmo que receba um numero inteiro
//e exiba se ele eh par ou impar.
Var
num1, valornum1 : inteiro


Inicio
escreva("Digite um numero: ")
leia(num1)
valornum1<-num1 % 2
se valornum1 = 0 entao
   escreva("par")
senao
escreva("impar")
fimSe

Fimalgoritmo