Algoritmo "Atividade3"

Var
   num1,num2,num3,num4,num5: real


Inicio
   escreval("digite o primeiro número: ")
   leia(num1)
   escreval("digite o segundo número: ")
   leia(num2)
   escreval("digite o terceiro número: ")
   leia(num3)
   escreval("digite o quarto número: ")
   leia(num4)
   escreval("digite o quinto número: ")
   leia(num5)
   escreva("os numeros digitado foram: ",num1,num2,num3,num4,num5)
Fimalgoritmo