Algoritmo "algoritmo24"

Var
num1,num2,par,impar,par1,impar1,pares,impares: inteiro
Inicio
escreva("digite o primeiro número: ")
leia(num1)
par <- num1 mod 2
impar <- num1 mod 2
escreval("o número",num1," e par ",par=0)
escreval("o número",num1," e impar ",impar<>0)

escreva("digite o primeiro número: ")
leia(num2)
par1<- num2 mod 2
impar1<-num2 mod 2
escreval("o número",num2," e par ",par1=0)
escreval("o número",num2," e impar ",impar1<>0)
Fimalgoritmo