Algoritmo "algoritmo22"
// Faça um programa que leia três números inteiros
// exiba o resultado da divisão inteira do primeiro
//pelo segundo e depois do resultado pelo terceiro.
Var
num1,num2,num3,divisao1,divisao2:inteiro

Inicio
escreval("Digite tres números inteiros: ")
leia(num1)
leia(num2)
leia(num3)
divisao1<-num1 DIV num2
divisao2<-divisao1 DIV NUM3
ESCREVA("a DIVISÃO deu : ",divisao2)





Fimalgoritmo