Algoritmo "algoritmo23"
//Faça um programa que leia um número inteiro e verifique se ele é par
//Exiba o resto da divisão do número por 2. (Obs: Não usar a função "Se").
Var
   numero:inteiro
   par,impar:inteiro

Inicio

   escreva("digite um número: ")
   leia(numero)
   par<-numero mod 2 and par=0
   impar<-numero mod 2 and impar<> 0
   escreval("o numero digitado",numero," é par",par=0)
   escreval("O numero digitado",numero, " e impar ",impar <>0)
   
   
Fimalgoritmo
