Algoritmo "aula1"

Var
nome : caractere
numero1, numero2,soma : inteiro



Inicio
escreval("digite o primeiro número: ")
leia(numero1)
escreval("digite o primeiro número: ")
leia(numero2)
soma := numero1+numero2
escreval("A soma do resultado foi: ",soma)

se(soma>0) e (soma<10)entao
escreval("unidade")
fimse
se(soma>10) e (soma<100)entao
escreval("dezena")
fimSe
se(soma>100) e (soma<1000)entao
escreval("centena")
FimSe


      

 
Fimalgoritmo

